eureka:
  instance:
    hostname: 127.0.0.1 #域名地址
    prefer-ip-address: true #使用ip注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false #是否注册到自身eureka服务器
    fetch-registry: false #是否从eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka地址
