spring:
  application:
    name: eureka-server #服务名称

server:
  port: 9647 #端口号
eureka:
  instance:
    hostname: 127.0.0.1 #域名地址
  client:
    register-with-eureka: false #是否注册到自身eureka服务器
    fetch-registry: false #是否从eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka地址
