info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"


spring:
  application:
    name: eureka-server #服务名称
  profiles:
    active: pre

server:
  port: 9647 #端口号
